# Generated by Django 3.2 on 2022-08-10 12:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(default=models.EmailField(max_length=100, unique=True), max_length=100)),
                ('region', models.CharField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('userType', models.CharField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('pass_last_updated', models.CharField(blank=True, max_length=254)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'ordering': ('-date_joined',),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(blank=True, default='', max_length=100)),
                ('branchCode', models.CharField(default='', max_length=100, unique=True)),
                ('branchManager', models.CharField(blank=True, default='', max_length=100)),
                ('branchMangerNo', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Branch',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.CharField(blank=True, default='', max_length=100)),
                ('customerName', models.CharField(blank=True, default='', max_length=100)),
                ('Phone', models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('addressState', models.CharField(blank=True, default='', max_length=100)),
                ('addressZipCode', models.CharField(blank=True, max_length=6)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('orderDate', models.CharField(blank=True, default='', max_length=100)),
                ('orderStatus', models.CharField(choices=[('in_transit', 'In Transit'), ('delivered', 'Delivered')], max_length=100)),
                ('EDD', models.CharField(blank=True, default='', max_length=100)),
                ('loanAppNo', models.CharField(blank=True, default='', max_length=100)),
                ('newLoanID', models.CharField(blank=True, default='', max_length=100)),
                ('invoiceNo', models.CharField(blank=True, default='', max_length=100)),
                ('batchNo', models.CharField(blank=True, default='', max_length=100)),
                ('branchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchID', to='mainApp.branch')),
            ],
            options={
                'verbose_name': 'Order',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, help_text='date create')),
                ('productName', models.CharField(blank=True, help_text='name a product', max_length=100)),
                ('productCode', models.CharField(max_length=100, unique=True)),
                ('sku', models.CharField(default='', max_length=100)),
                ('gst', models.CharField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('disbursementStatus', models.CharField(choices=[('disbursed', 'Disbursed'), ('not_disbursed', 'Not Disbursed')], max_length=100)),
                ('disbursementDate', models.CharField(blank=True, default='', max_length=100)),
                ('updatedDate', models.CharField(blank=True, default='', max_length=100)),
                ('stockStatus', models.CharField(blank=True, default='', max_length=100)),
                ('adminUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminUserID', to=settings.AUTH_USER_MODEL)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderID', to='mainApp.order')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productID', to='mainApp.product')),
                ('stockBranchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockBranchID', to='mainApp.branch')),
            ],
            options={
                'verbose_name': 'Stock',
                'ordering': ('-id',),
            },
        ),
    ]
