# Generated by Django 3.2 on 2022-08-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_stockreceive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stockStatus',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='', max_length=100),
        ),
    ]
