# Generated by Django 3.2 on 2022-08-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_stock_stockstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReceiveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
