# Generated by Django 3.2 on 2022-08-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_printinovice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
