# Generated by Django 3.2 on 2022-09-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_disbursementreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('mfi_branch', 'MFI_BRANCH'), ('mfi_ho', 'MFI_HO'), ('admin_penco', 'ADMIN_PENCO')], max_length=50, null=True),
        ),
    ]
