# Generated by Django 3.2 on 2022-09-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
    ]
