# Generated by Django 3.2 on 2022-10-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20220905_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementreport',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
