# Generated by Django 3.2 on 2022-10-29 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_disbursementreport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='branchID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='adminUserID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminUserID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock',
            name='disbursementStatus',
            field=models.CharField(choices=[('disbursed', 'Disbursed'), ('not_disbursed', 'Not Disbursed')], default='disbursed', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='orderID',
            field=models.ForeignKey(default=11, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderID', to='mainApp.order'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productID', to='mainApp.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stockBranchID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockBranchID', to='mainApp.branch'),
        ),
    ]
