# Generated by Django 3.2 on 2022-10-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20221031_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='in_transit', max_length=100),
        ),
    ]
