# Generated by Django 3.2 on 2022-11-23 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_auto_20221123_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='BranchID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BranchID', to='mainApp.branch'),
        ),
    ]
