# Generated by Django 3.2 on 2022-11-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_stock_branchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='orderID',
            field=models.ForeignKey(blank=True, default=11, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderID', to='mainApp.order'),
        ),
    ]
