# Generated by Django 3.2 on 2022-11-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_alter_stock_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='disbursementStatus',
            field=models.CharField(choices=[('Disbursed', 'Disbursed'), ('NotDisbursed', 'Not Disbursed')], default='Notdisbursed', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='orderID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderID', to='mainApp.order'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stockStatus',
            field=models.CharField(blank=True, choices=[('InTransit', 'In Transit'), ('Delivered', 'Delivered')], default='InTransit', max_length=100),
        ),
    ]
