# Generated by Django 3.2 on 2022-11-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_auto_20221123_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
    ]
