# Generated by Django 3.2 on 2022-11-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_order_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='orderID',
        ),
        migrations.AddField(
            model_name='order',
            name='stockID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockID', to='mainApp.stock'),
        ),
    ]
