# Generated by Django 3.2 on 2022-11-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_auto_20221128_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
