# Generated by Django 3.2 on 2022-12-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='loanAppNo',
            new_name='loanNo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='batchNo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='batch_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loan_officer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loan_officer_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='newLoanID',
        ),
        migrations.AlterField(
            model_name='order',
            name='loanNo',
            field=models.CharField(blank=True, db_column='loanAppNo', default='', max_length=100),
        ),
    ]
