# Generated by Django 3.2 on 2022-12-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_auto_20221207_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='loan_approval_date',
            new_name='loan_date',
        ),
        migrations.AddField(
            model_name='order',
            name='loanStatus',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='loanType',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='loan_date',
            field=models.CharField(blank=True, db_column='loan_approval_date', default='', max_length=100),
        ),
    ]
