# Generated by Django 3.2 on 2022-12-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_auto_20221207_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_password',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_username',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
