# Generated by Django 3.2 on 2022-12-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0028_auto_20221217_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_password',
        ),
    ]
