# Generated by Django 3.2 on 2022-12-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_remove_branch_branch_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_password',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
