# Generated by Django 3.2 on 2022-12-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_branch_branch_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='disbursementStatus',
            field=models.CharField(choices=[('Disbursed', 'Disbursed'), ('NotDisbursed', 'Not Disbursed')], default='NotDisbursed', max_length=100),
        ),
    ]
