# Generated by Django 3.2 on 2023-01-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0031_alter_stock_disbursementstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='loanStatus',
        ),
    ]
