# Generated by Django 3.2 on 2023-01-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0033_order_loanstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='updatedDate',
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.product', verbose_name='Product'),
        ),
    ]
