# Generated by Django 3.2 on 2023-01-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_auto_20230105_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
