# Generated by Django 3.2 on 2023-01-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0035_stock_updateddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='stock',
            name='BranchID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BranchID', to='mainApp.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productID', to='mainApp.product', verbose_name='Product'),
        ),
    ]
