# Generated by Django 3.2 on 2023-01-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0037_auto_20230127_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
