# Generated by Django 3.2 on 2023-07-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0040_stock_orderdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliername', models.CharField(blank=True, default='', max_length=100, verbose_name='Supplier Name')),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('zipcode', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=12, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Supplier',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_password',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_username',
            field=models.EmailField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
