# Generated by Django 3.2 on 2023-07-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0041_auto_20230704_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='zipcode',
        ),
    ]
