# Generated by Django 3.2 on 2023-07-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0042_remove_supplier_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
