# Generated by Django 3.2 on 2023-07-05 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0046_remove_quantity_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='mainApp.purchase', verbose_name='Purchase'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=201, verbose_name='Quantity'),
        ),
    ]
