# Generated by Django 3.2 on 2023-07-05 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0047_auto_20230705_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'ordering': ('-id',), 'verbose_name': 'Quantity'},
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=201, verbose_name='Qty'),
        ),
        migrations.CreateModel(
            name='HubQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, default='', max_length=201, verbose_name='Qty')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemname', to='mainApp.product', verbose_name='Item Name')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasename', to='mainApp.purchase', verbose_name='Purchase Name')),
                ('supplierqty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierqty', to='mainApp.quantity', verbose_name='Total Quantity')),
            ],
            options={
                'verbose_name': 'Hub Quantity',
                'ordering': ('-id',),
            },
        ),
    ]
