# Generated by Django 3.2 on 2023-07-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0048_auto_20230705_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubquantity',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub', to='mainApp.hub', verbose_name='Hub Name'),
        ),
    ]
