# Generated by Django 3.2 on 2023-07-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0049_hubquantity_hub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HubQuantity',
        ),
    ]
