# Generated by Django 3.2 on 2023-07-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0050_delete_hubquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, default='', max_length=201, verbose_name='Qty')),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub', to='mainApp.hub', verbose_name='Hub Name')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemname', to='mainApp.product', verbose_name='Item Name')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasename', to='mainApp.supplier', verbose_name='Supplier Name')),
                ('supplierqty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierqty', to='mainApp.quantity', verbose_name='Supplier Quantity')),
            ],
            options={
                'verbose_name': 'Hub Quantity',
                'ordering': ('-id',),
            },
        ),
    ]
