# Generated by Django 3.2 on 2023-07-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0053_hubquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='remainingquantity',
            field=models.CharField(blank=True, default='', max_length=201, verbose_name='Remaining Quantity'),
        ),
    ]
