# Generated by Django 3.2 on 2023-07-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0054_quantity_remainingquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='contactname',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Contact Name'),
        ),
        migrations.AddField(
            model_name='hub',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Hub Name'),
        ),
    ]
