# Generated by Django 3.2 on 2023-07-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0055_auto_20230714_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubquantity',
            name='supplierqty',
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponumber', models.CharField(blank=True, default='', max_length=201, verbose_name='Po Number')),
                ('quantity', models.CharField(blank=True, default='', max_length=201, verbose_name='Quantity')),
                ('stockfrom', models.CharField(blank=True, default='', max_length=201, verbose_name='From')),
                ('stockto', models.CharField(blank=True, default='', max_length=201, verbose_name='To')),
                ('stockStatus', models.CharField(blank=True, choices=[('InTransit', 'In Transit'), ('Delivered', 'Delivered')], default='InTransit', max_length=100)),
                ('transitdate', models.DateField(auto_now=True)),
                ('hubname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubname', to='mainApp.hub', verbose_name='Name')),
                ('itemname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='mainApp.product', verbose_name='Item Name')),
                ('suppliername', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='mainApp.supplier', verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Transit',
                'ordering': ('-id',),
            },
        ),
    ]
