# Generated by Django 3.2 on 2023-07-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0056_auto_20230715_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transit',
        ),
    ]
