# Generated by Django 3.2 on 2023-07-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0061_auto_20230717_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stockfrom',
            field=models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Hub', 'Hub')], default='', max_length=201, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stockto',
            field=models.CharField(blank=True, choices=[('Hub', 'Hub'), ('Branch', 'Branch')], default='', max_length=201, verbose_name='To'),
        ),
    ]
