# Generated by Django 3.2 on 2023-07-18 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0062_auto_20230717_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectfrom', models.CharField(blank=True, choices=[('Hub', 'Hub')], default=False, max_length=100, verbose_name='From')),
                ('SelectTo', models.CharField(blank=True, choices=[('Hub', 'Hub'), ('Branch', 'Branch')], default=False, max_length=100, verbose_name='To')),
                ('branchdestination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchnamedestination', to='mainApp.branch', verbose_name='Destination')),
                ('hubdestination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubdestination', to='mainApp.hub', verbose_name='Destination')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='mainApp.hub')),
            ],
        ),
    ]
