# Generated by Django 3.2 on 2023-07-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0063_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ('-id',), 'verbose_name': 'Transfer'},
        ),
        migrations.AddField(
            model_name='transfer',
            name='receiveddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transferdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
