# Generated by Django 3.2 on 2023-07-18 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0064_auto_20230718_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferablestock', models.CharField(blank=True, default=False, max_length=100, verbose_name='Transferable Stock')),
                ('stocktransfered', models.CharField(blank=True, default=False, max_length=100, verbose_name='Stock to be Transfered')),
                ('comment', models.CharField(blank=True, default=False, max_length=100)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Productname', to='mainApp.product')),
            ],
            options={
                'verbose_name': 'Transfer Quantity',
                'ordering': ('-id',),
            },
        ),
    ]
