# Generated by Django 3.2 on 2023-07-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0067_auto_20230725_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferquantity',
            name='hub',
        ),
    ]
