# Generated by Django 3.2 on 2023-07-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0068_remove_transferquantity_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='stockStatus',
            field=models.CharField(blank=True, choices=[('InTransit', 'In Transit'), ('Delivered', 'Delivered')], default='InTransit', max_length=100),
        ),
    ]
