# Generated by Django 3.2 on 2023-07-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0069_transfer_stockstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='hubname',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='suppliername',
        ),
    ]
