# Generated by Django 3.2 on 2023-07-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0070_auto_20230725_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stockfromname',
            field=models.CharField(blank=True, max_length=201, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stocktoname',
            field=models.CharField(blank=True, max_length=201, null=True, verbose_name='Name'),
        ),
    ]
