# Generated by Django 3.2 on 2023-07-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0071_auto_20230725_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='updatedDate',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='stockStatus',
        ),
    ]
