# Generated by Django 3.2 on 2023-07-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0074_remove_stock_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Transfer Date'),
        ),
    ]
