# Generated by Django 3.2 on 2023-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0075_stock_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stocktype',
            field=models.CharField(blank=True, choices=[('Transit', 'Transit'), ('Transfer', 'Transfer')], default='', max_length=100, verbose_name='Type'),
        ),
    ]
