# Generated by Django 3.2 on 2023-07-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0076_alter_stock_stocktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stocktoname',
        ),
    ]
