# Generated by Django 3.2 on 2023-07-26 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0077_remove_stock_stocktoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stocktoBranchname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BranchID', to='mainApp.branch', verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stocktoHubname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HubID', to='mainApp.hub', verbose_name='Name'),
        ),
    ]
