# Generated by Django 3.2 on 2023-07-27 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0079_auto_20230726_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stockfromname',
        ),
        migrations.AddField(
            model_name='stock',
            name='stockfromHubname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockHubId', to='mainApp.hub', verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stockfromSuppliername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SupplierID', to='mainApp.supplier', verbose_name='Name'),
        ),
    ]
