# Generated by Django 3.2 on 2023-08-11 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0080_auto_20230727_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustmentNo', models.CharField(editable=False, max_length=200, unique=True)),
                ('adjustmentfor', models.CharField(blank=True, choices=[('Hub', 'Hub'), ('Branch', 'Branch')], default=False, max_length=100, verbose_name='Adjustment For')),
                ('adjustmentType', models.CharField(blank=True, choices=[('OpeningStock', 'Opening Stock'), ('Increase', 'Increase'), ('Decrease', 'Decrease')], default=False, max_length=100, verbose_name='Adjustment Type')),
                ('comment', models.CharField(blank=True, default='', max_length=100)),
                ('adjustmentDate', models.DateField(auto_now_add=True, null=True, verbose_name='Adjustment Date')),
                ('adjustableBranch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustableBranch', to='mainApp.branch', verbose_name='Select Adjustable')),
                ('adjustableHub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustableHub', to='mainApp.hub', verbose_name='Select Adjustable')),
            ],
            options={
                'verbose_name': 'Adjustment',
                'ordering': ('-id',),
            },
        ),
    ]
