# Generated by Django 3.2 on 2023-08-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0081_adjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(blank=True, default='', max_length=100, verbose_name='Stock To Be Adjusted')),
                ('adjust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustmentId', to='mainApp.adjustment')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustmentitem', to='mainApp.product')),
            ],
        ),
    ]
