# Generated by Django 3.2 on 2023-08-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0082_adjustmentstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjustmentstock',
            options={'ordering': ('-id',), 'verbose_name': 'Adjustment Stock'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='stocktype',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Type'),
        ),
    ]
