# Generated by Django 3.2 on 2023-08-18 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0083_auto_20230814_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='transferid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TransferId', to='mainApp.transfer', verbose_name='Transfer'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stockfrom',
            field=models.CharField(blank=True, default='', max_length=201, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transferdate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Tranfer Date'),
        ),
    ]
