# Generated by Django 3.2 on 2023-08-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0085_remove_stock_transferid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stockID',
        ),
    ]
