# Generated by Django 3.2 on 2023-08-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0086_remove_order_stockid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='totalquantity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
