# Generated by Django 3.2 on 2023-08-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0088_auto_20230825_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hubbalance',
            options={'ordering': ('-id',), 'verbose_name': 'Hub Balance'},
        ),
    ]
