# Generated by Django 3.2 on 2023-08-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0089_alter_hubbalance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubbalance',
            name='openingstock',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Opening Stock'),
        ),
        migrations.AddField(
            model_name='hubbalance',
            name='receivedstock',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Received Stock'),
        ),
        migrations.AddField(
            model_name='hubbalance',
            name='transferstock',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Transfer Stock'),
        ),
    ]
