# Generated by Django 3.2 on 2023-09-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0094_stock_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='File'),
        ),
    ]
