# Generated by Django 3.2 on 2023-09-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0095_alter_stock_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubbalance',
            name='receivedstock',
        ),
        migrations.RemoveField(
            model_name='hubbalance',
            name='transferstock',
        ),
        migrations.CreateModel(
            name='BranchBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openingstock', models.CharField(blank=True, default='', max_length=100, verbose_name='Opening Stock')),
                ('closingstock', models.CharField(blank=True, default='', max_length=100, verbose_name='Closing Stock')),
                ('created_at', models.DateField(blank=True, null=True)),
                ('branchid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchBalanceId', to='mainApp.branch', verbose_name='Name')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchItemId', to='mainApp.product', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Branch Balance',
                'ordering': ('-id',),
            },
        ),
    ]
