# Generated by Django 3.2 on 2023-09-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0096_auto_20230913_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='adjustmentDate',
            field=models.DateField(blank=True, null=True, verbose_name='Adjustment Date'),
        ),
    ]
