# Generated by Django 3.2 on 2023-10-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0098_alter_adjustment_adjustmentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverydate',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Date of Delivery'),
        ),
    ]
