# Generated by Django 3.2 on 2023-11-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0100_remove_order_deliverydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='stockStatus',
            field=models.CharField(blank=True, choices=[('InTransit', 'In Transit'), ('Delivered', 'Delivered')], default='InTransit', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_delivery',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Date of Delivery'),
        ),
    ]
