# Generated by Django 3.2 on 2023-11-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0101_auto_20231116_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='stockStatus',
            new_name='transferStatus',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transferStatus',
            field=models.CharField(blank=True, choices=[('InTransit', 'In Transit'), ('Delivered', 'Delivered')], db_column='stockStatus', default='InTransit', max_length=100),
        ),
    ]
