# Generated by Django 3.2 on 2023-11-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0104_alter_requisition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='chalanNumber',
            field=models.CharField(blank=True, db_column='Chalan Number', max_length=201),
        ),
    ]
