# Generated by Django 3.2 on 2023-11-21 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0105_requisition_chalannumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='requisitionno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Requisition', to='mainApp.requisition', verbose_name='Requisition'),
        ),
    ]
