# Generated by Django 3.2 on 2023-11-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0106_transfer_requisitionno'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='quantity',
            field=models.CharField(blank=True, max_length=201),
        ),
    ]
