# Generated by Django 3.2 on 2023-11-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0108_transfer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='remarks',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
