# Generated by Django 3.2 on 2023-11-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0109_transfer_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='hubName',
        ),
    ]
