# Generated by Django 3.2 on 2023-11-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0110_remove_requisition_hubname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='requisitionDate',
            field=models.DateField(blank=True, null=True, verbose_name='Requisition Date'),
        ),
    ]
