# Generated by Django 3.2 on 2023-11-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0111_alter_requisition_requisitiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='transit',
            name='remarks',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
