# Generated by Django 3.2 on 2023-11-23 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0112_auto_20231123_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='hubBranch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.hub', verbose_name='Hub'),
        ),
    ]
