# Generated by Django 3.2 on 2023-11-23 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0113_branch_hubbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='hubBranch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubBranch', to='mainApp.hub', verbose_name='Hub'),
        ),
    ]
