# Generated by Django 3.2 on 2023-11-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0114_alter_branch_hubbranch'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=201)),
                ('address', models.CharField(blank=True, db_column='Full Address', max_length=201)),
                ('gst', models.CharField(blank=True, db_column='GST Number', max_length=201)),
                ('cinNumber', models.CharField(blank=True, db_column='CIN Number', max_length=201)),
            ],
            options={
                'verbose_name': 'State',
                'ordering': ('-id',),
            },
        ),
    ]
