# Generated by Django 3.2 on 2023-11-25 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0115_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HubState', to='mainApp.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PoState', to='mainApp.state', verbose_name='State'),
        ),
    ]
