# Generated by Django 3.2 on 2023-12-01 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0117_auto_20231201_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='salehuub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Salehub', to='mainApp.hub', verbose_name='Sale Hub'),
        ),
    ]
