# Generated by Django 3.2 on 2023-12-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0121_alter_transfer_transferdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transferdate',
            field=models.DateField(blank=True, null=True, verbose_name='Tranfer Date'),
        ),
    ]
