# Generated by Django 3.2 on 2023-12-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0122_alter_transfer_transferdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='transitdate',
            field=models.DateField(),
        ),
    ]
